desp: "使用dqn玩atari中space-invaders"
option:
    # env
    env_path: "/home/caory/github/ReinforcementLearning/pong/pong.bin"

    # model
    n_action: &n_action 2
    n_history: &n_history 4
    image_y_size: &image_y_size 84
    image_x_size: &image_x_size 84
    image_channel: &image_channel 4
    is_weight_decay: False
    weight_decay_scale: 0.0001
    data_format: "channels_first"
    is_time_major: True
    update_function: "adam"
    is_use_double: True
    is_use_dueling: True

    # data
    logs_dir: "/home/caory/data/PDFInsight/deep_rl/logs/"
    seq: "pong_v1"
    model_name: "pg"
    log_path: "/home/caory/data/PDFInsight/deep_rl/logs/space_invaders_v1/train_logs/pg.log"

    # train
    n_producer: 1
    n_consumer: 1
    batch_size: 64
    init_memory_size: 50000
    max_memory_size: 1000000
    n_gpus: 1
    gpus: "7"
    train_gpus: "0"
    learning_rate: 0.01
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.1
    epsilon_decay: 250000
    epoch_start: 1
    max_frame: 10000000
    save_epoch_freq: 500
    log_frame_freq: 5000
    update_frame_freq: 5000
    seed: 12

    # data_size
    data_size:
        image:
            dtype: "float32"
            size:
                - *image_y_size
                - *image_x_size
                - *image_channel

        action_mask:
            dtype: "float32"
            size:
                - *n_action

        reward:
            dtype: "float32"
            size:
                - 1

        coef:
            dtype: "float32"
            size:
                - 1

# framework
network:
    classify_input_size: &classify_input_size 4
    classify_input_shape:
        - *classify_input_size

    layers:
        target:
            - {name: "target_dense1", type: "dense", hidden_dim: 16, activation: "relu", bn: False, prev: "none", input_shape: "classify_input_shape"}
            - {name: "target_dense2", type: "dense", hidden_dim: 2, activation: "none", bn: False, prev: "target_dense1"}